version: "2"

services:

  resolver:
    build: ./resolver/.
    ports:
      - 53:53
    networks:
      interne:
          ipv4_address: 192.168.8.3
    volumes:
      - ./RESOLVER/named.conf:/etc/bind/named.conf
    container_name: resolver
    command: "named -c /etc/bind/named.conf -g"

networks:

  interne:
      ipam:
          driver: default
          config:
              - subnet: 192.168.8.0/24
                gateway:  192.168.8.254
                
                
services:

  soa:
    build: ./soa/.
    ports:
      - 53:53
    networks:
      interne:
          ipv4_address: 192.168.8.2
    volumes:
      - ./RESOLVER/named.conf:/etc/bind/named.conf
    container_name: resolver
    command: "named -c /etc/bind/named.conf -g"

networks:

  interne:
      ipam:
          driver: default
          config:
              - subnet: 192.168.8.0/24
                gateway:  192.168.8.254