version: "2"

services:

  resolver:
    build: ./resolver/.
    ports:
      - 53:53
    networks:
      interne:
          ipv4_address: 192.168.8.3
    volumes:
      - ./resolver/named.conf:/etc/bind/named.conf
    container_name: resolver
    command: "named -c /etc/bind/named.conf -g"
   

  soa:
    build: ./soa/.
    ports:
      - 53:53
    networks:
      interne:
          ipv4_address: 192.168.8.2
    volumes:
      - ./soa/named.conf:/etc/bind/named.conf
      - ./soa/zone/8.168.192.in-addr.arpa:/etc/bind/master/8.168.192.in-addr.arpa
      - ./soa/zone/intranet.ephecti.be:/etc/bind/master/intranet.ephecti.be
      - ./soa/resolv.conf:/etc/resolv.conf
    container_name: soa
    
    command: "named -c /etc/bind/named.conf -g"
    
  erp:
    build: ./erp/.
    ports:
      - 8080:80
    networks:
      interne:
          ipv4_address: 192.168.8.1
    volumes:
      - ./erp/www:/var/www/html/
      - ./erp/.htaccess:/var/www/html/.htaccess
      - ./erp/apache2.conf:/etc/apache2/apache2.conf
    links:
      - db
    container_name: erp
    
  db:
    image: mysql:8.0.16
    ports: 
        - "3306:3306"
    networks:
      interne:
          ipv4_address: 192.168.8.4
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - ./erp/datas:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_ROOT_PASSWORD: test
        
  compta:
    build: ./entreprise/compta/.
    networks:
      reseau_entreprise:
          ipv4_address: 192.168.1.1
    volumes:
      - ./entreprise/compta/resolv.conf:/etc/resolv.conf
    container_name: compta
    
    
volumes:
    persistent:     


networks:

  interne:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 192.168.8.0/24
                gateway:  192.168.8.254
                
 
 
  reseau_entreprise:
      ipam:
          driver: default
          config:
              - subnet: 192.168.1.0/24
                gateway:  192.168.1.254
